# Generated by Django 5.0.3 on 2024-03-05 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('genre', models.CharField(max_length=50)),
                ('time', models.TimeField(max_length=30)),
                ('director', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='seat_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.IntegerField()),
                ('seat_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='theatre_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thatre_id', models.IntegerField()),
                ('loaction', models.CharField(max_length=50)),
                ('t_name', models.CharField(max_length=50)),
                ('screen_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='show_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_id', models.IntegerField()),
                ('start_time', models.TimeField(max_length=10)),
                ('date', models.DateField(max_length=10)),
                ('end_time', models.TimeField(max_length=10)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_your_ticket.movie_info')),
                ('theatre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='find_your_ticket.theatre_info')),
            ],
        ),
    ]
