# Generated by Django 4.2.11 on 2024-03-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_your_ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_info',
            name='time',
            field=models.CharField(max_length=30),
        ),
    ]
