# Generated by Django 4.2.11 on 2024-03-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_your_ticket', '0002_alter_movie_info_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_info',
            name='movie_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
